### ISSUE TITLE
Problem using non-file serializer for options, fx a database

### ISSUE THREAD

**Issue by JakobYde** [exilon/QuickLib#89]
It is not possible to load options from a database, due to the FileExists check. 
My propositions are to either make the variables used here protected, allow for passing a function to perform the 'file/database exists' check or simply by removing the check and handling this in the serializers. 

I can make a pull-request with whichever you prefer, if this is of interest :)

```
procedure TOptionsContainer.Load(aFailOnSectionNotExists : Boolean = False);
var
  option : TOptions;
begin
  if 

> FileExists(fFilename)

 then
  begin
    if not fSerializer.Load(fFilename,fSections,aFailOnSectionNotExists) then Save;
    if not fLoaded then
    begin
      fLoaded := True;
      if Assigned(fOnConfigLoaded) then fOnConfigLoaded;
    end
    else if Assigned(fOnConfigReloaded) then fOnConfigReloaded;
  end
  else
  begin
    //if not exists file get default values
    for option in fSections do option.DefaultValues;
    //creates default file
    Save;
  end;
end;

procedure TOptionsContainer.LoadSection(aOptions : TOptions);
begin
  if 

> FileExists(fFilename) 

then
  begin
    if not fSerializer.LoadSection(fFilename,fSections,aOptions) then Save;
  end;
end;
```

**Comment by exilon** [comment]
I did a small refactor. Now there is a TFileOptionsContainer for file based configs and original TOptionsContainer allowing any serializer you want to create.

**Comment by GT-JAYM** [comment]
Nice, thanks! I managed to make a workaround since then, so I don't know if I'll get around to using this, but hopefully someone else will :P

In `TOptionsContainer.Load`, you missed these file related comments, but otherwise it looks good :)
```
    //if not exists file get default values
    for option in fSections do option.DefaultValues;
    //creates default file
```

**Comment by exilon** [comment]
Thanks, you’re welcome to make a pull-request with your db serializer provider. I’ve preparing a Windows registry serializer.

Best regards,

Kike Pérez

De: Jakob Yde-Madsen
Enviado: lunes, 13 de diciembre de 2021 9:52
Para: exilon/QuickLib
CC: Exilon; Comment
Asunto: Re: [exilon/QuickLib] Problem using non-file serializer for options,fx a database (Issue #89)

Nice, thanks! I managed to make a workaround since then, so I don't know if I'll get around to using this, but hopefully someone else will :P
In TOptionsContainer.Load, you missed these file related comments, but otherwise it looks good :)
    //if not exists file get default values
    for option in fSections do option.DefaultValues;
    //creates default file
